spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/goormthon
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create #애플리케이션 실행 시점에 내가 가지공 있는 엔티티를 다 지우고 테이블 생성
    properties:
      hibernate:
        #        show_sql: true  jpa나 hibernate가 생성하는 로그가 보임 (system.out을 이용)
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug # jpa나 hibernate가 생성하는 로그가 보임 (로그를 통해서 보임)